const errorMsg = {
  invalidUrl: 'This is not the web page you are looking for.',
  generalError: 'There was an error on the server. Please try again in a moment.',
  invalidSignup: 'We can\'t sign up for unknown reasons',
  invalidLogin: 'We can\'t login for unknown reasons',
  nothingToken: 'We can\'t find a token. Please login again.',
  tokenExpired: 'You should login again because login valid time is expired',
  invalidToken: 'There was a error with login. Please login again.',
  invalidSave: 'We can\'t save for unknown reasons',
  invalidImgs: 'We can\'t get pictures or We can\'t save pictures for unknown reasons',
  invalidCategory: 'There is a invalid treasure category. Try again.',
  noneCountry: 'There isn\'t a selected country. Try again.',
  noneName: 'There isn\'t a treasure name. Try again.',
  invalidExpiration: 'Try again. Expiration must be later than now',
  noneLocation: 'We can\'t get a treasure location Try again',
  noneDescription: 'Let me know about your treasure. Anything!.',
  nonePictures: 'You should take pictures about location of treasure. Click "Camera" Or "Gallery".',
  noneMap: 'You should inputed a your treasure location. Click "Map" button, and confirm location.',
  invalidTreasures: 'We can\'t find treasures informations for unknown reasons. Try again.',
  invalideSelectedTreasure: 'We can\'t find selected treasure for unknown reasons. Try again.',
  duplicate: 'You can\'t take the treasure you registered for.',
  invalidDate: 'The expiration date has passed.',
  invalidDeleteUser: 'You can delete the treasure you registered for.',
  failDelete: 'We can\'t delete for unknown reasons.',
  failTakenTreasure: 'We can\'t delete treasure is taken',
  failImageSize: 'Images can be uploaded up to 10MByte.',
};

module.exports = { errorMsg };
